[package]
name = "sssp_delta"
version = "0.1.0"
edition = "2021"

[dependencies]
lamellar = "0.6.1"
rayon = "1.10.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.38.1", features = ["full"] }
