[package]
name = "lamellar-rmat"
version = "0.1.0"
edition = "2021"

[dependencies]
dist-structs = { version = "0.1.0", path = "../dist-structs" }
lamellar = "0.6.1"
rmat-generator = {path = "../rmat-generator"}
